//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
///Represents a strongly typed in-memory cache of data.
///</summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
[global::System.Serializable()]
[global::System.ComponentModel.DesignerCategoryAttribute("code")]
[global::System.ComponentModel.ToolboxItem(true)]
[global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
[global::System.Xml.Serialization.XmlRootAttribute("Factura")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
public partial class Factura : global::System.Data.DataSet {
    
    private VFacturaDataTable tableVFactura;
    
    private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public Factura() {
        this.BeginInit();
        this.InitClass();
        global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
        base.Tables.CollectionChanged += schemaChangedHandler;
        base.Relations.CollectionChanged += schemaChangedHandler;
        this.EndInit();
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    protected Factura(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
            base(info, context, false) {
        if ((this.IsBinarySerialized(info, context) == true)) {
            this.InitVars(false);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler1;
            this.Relations.CollectionChanged += schemaChangedHandler1;
            return;
        }
        string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
        if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
            global::System.Data.DataSet ds = new global::System.Data.DataSet();
            ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            if ((ds.Tables["VFactura"] != null)) {
                base.Tables.Add(new VFacturaDataTable(ds.Tables["VFactura"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        else {
            this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
        }
        this.GetSerializationData(info, context);
        global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
        base.Tables.CollectionChanged += schemaChangedHandler;
        this.Relations.CollectionChanged += schemaChangedHandler;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.Browsable(false)]
    [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
    public VFacturaDataTable VFactura {
        get {
            return this.tableVFactura;
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.BrowsableAttribute(true)]
    [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
    public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
        get {
            return this._schemaSerializationMode;
        }
        set {
            this._schemaSerializationMode = value;
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public new global::System.Data.DataTableCollection Tables {
        get {
            return base.Tables;
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public new global::System.Data.DataRelationCollection Relations {
        get {
            return base.Relations;
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    protected override void InitializeDerivedDataSet() {
        this.BeginInit();
        this.InitClass();
        this.EndInit();
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public override global::System.Data.DataSet Clone() {
        Factura cln = ((Factura)(base.Clone()));
        cln.InitVars();
        cln.SchemaSerializationMode = this.SchemaSerializationMode;
        return cln;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    protected override bool ShouldSerializeTables() {
        return false;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    protected override bool ShouldSerializeRelations() {
        return false;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
        if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
            this.Reset();
            global::System.Data.DataSet ds = new global::System.Data.DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["VFactura"] != null)) {
                base.Tables.Add(new VFacturaDataTable(ds.Tables["VFactura"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        else {
            this.ReadXml(reader);
            this.InitVars();
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
        global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
        this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
        stream.Position = 0;
        return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal void InitVars() {
        this.InitVars(true);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal void InitVars(bool initTable) {
        this.tableVFactura = ((VFacturaDataTable)(base.Tables["VFactura"]));
        if ((initTable == true)) {
            if ((this.tableVFactura != null)) {
                this.tableVFactura.InitVars();
            }
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    private void InitClass() {
        this.DataSetName = "Factura";
        this.Prefix = "";
        this.Namespace = "http://tempuri.org/Factura.xsd";
        this.EnforceConstraints = true;
        this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        this.tableVFactura = new VFacturaDataTable();
        base.Tables.Add(this.tableVFactura);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    private bool ShouldSerializeVFactura() {
        return false;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
        if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
            this.InitVars();
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
        Factura ds = new Factura();
        global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
        global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
        global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
        any.Namespace = ds.Namespace;
        sequence.Items.Add(any);
        type.Particle = sequence;
        global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
        if (xs.Contains(dsSchema.TargetNamespace)) {
            global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
            global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
            try {
                global::System.Xml.Schema.XmlSchema schema = null;
                dsSchema.Write(s1);
                for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                    schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                    s2.SetLength(0);
                    schema.Write(s2);
                    if ((s1.Length == s2.Length)) {
                        s1.Position = 0;
                        s2.Position = 0;
                        for (; ((s1.Position != s1.Length) 
                                    && (s1.ReadByte() == s2.ReadByte())); ) {
                            ;
                        }
                        if ((s1.Position == s1.Length)) {
                            return type;
                        }
                    }
                }
            }
            finally {
                if ((s1 != null)) {
                    s1.Close();
                }
                if ((s2 != null)) {
                    s2.Close();
                }
            }
        }
        xs.Add(dsSchema);
        return type;
    }
    
    public delegate void VFacturaRowChangeEventHandler(object sender, VFacturaRowChangeEvent e);
    
    /// <summary>
    ///Represents the strongly named DataTable class.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
    public partial class VFacturaDataTable : global::System.Data.TypedTableBase<VFacturaRow> {
        
        private global::System.Data.DataColumn columnnhc;
        
        private global::System.Data.DataColumn columnnombre;
        
        private global::System.Data.DataColumn columnapellido1;
        
        private global::System.Data.DataColumn columnapellido2;
        
        private global::System.Data.DataColumn columnnif;
        
        private global::System.Data.DataColumn columncpostal;
        
        private global::System.Data.DataColumn columnPROV;
        
        private global::System.Data.DataColumn columnPOB;
        
        private global::System.Data.DataColumn columnDIREC;
        
        private global::System.Data.DataColumn columnPais;
        
        private global::System.Data.DataColumn columnbasica_id;
        
        private global::System.Data.DataColumn columndescripcion;
        
        private global::System.Data.DataColumn columndireccion;
        
        private global::System.Data.DataColumn columnpoblacion;
        
        private global::System.Data.DataColumn columnprovincia;
        
        private global::System.Data.DataColumn columntelefono;
        
        private global::System.Data.DataColumn columnfax;
        
        private global::System.Data.DataColumn columnpostal;
        
        private global::System.Data.DataColumn columncif;
        
        private global::System.Data.DataColumn columnfactura_id;
        
        private global::System.Data.DataColumn columnfecha;
        
        private global::System.Data.DataColumn columntratamiento_id;
        
        private global::System.Data.DataColumn columnDescT;
        
        private global::System.Data.DataColumn columnimporte;
        
        private global::System.Data.DataColumn columndescuento;
        
        private global::System.Data.DataColumn columndebe;
        
        private global::System.Data.DataColumn columnhaber;
        
        private global::System.Data.DataColumn columnpeca;
        
        private global::System.Data.DataColumn columnrecibo_id;
        
        private global::System.Data.DataColumn columnvalorrec;
        
        private global::System.Data.DataColumn columnpoliza;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VFacturaDataTable() {
            this.TableName = "VFactura";
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal VFacturaDataTable(global::System.Data.DataTable table) {
            this.TableName = table.TableName;
            if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                this.CaseSensitive = table.CaseSensitive;
            }
            if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                this.Locale = table.Locale;
            }
            if ((table.Namespace != table.DataSet.Namespace)) {
                this.Namespace = table.Namespace;
            }
            this.Prefix = table.Prefix;
            this.MinimumCapacity = table.MinimumCapacity;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected VFacturaDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context) {
            this.InitVars();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn nhcColumn {
            get {
                return this.columnnhc;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn nombreColumn {
            get {
                return this.columnnombre;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn apellido1Column {
            get {
                return this.columnapellido1;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn apellido2Column {
            get {
                return this.columnapellido2;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn nifColumn {
            get {
                return this.columnnif;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn cpostalColumn {
            get {
                return this.columncpostal;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn PROVColumn {
            get {
                return this.columnPROV;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn POBColumn {
            get {
                return this.columnPOB;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn DIRECColumn {
            get {
                return this.columnDIREC;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn PaisColumn {
            get {
                return this.columnPais;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn basica_idColumn {
            get {
                return this.columnbasica_id;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn descripcionColumn {
            get {
                return this.columndescripcion;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn direccionColumn {
            get {
                return this.columndireccion;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn poblacionColumn {
            get {
                return this.columnpoblacion;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn provinciaColumn {
            get {
                return this.columnprovincia;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn telefonoColumn {
            get {
                return this.columntelefono;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn faxColumn {
            get {
                return this.columnfax;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn postalColumn {
            get {
                return this.columnpostal;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn cifColumn {
            get {
                return this.columncif;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn factura_idColumn {
            get {
                return this.columnfactura_id;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn fechaColumn {
            get {
                return this.columnfecha;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn tratamiento_idColumn {
            get {
                return this.columntratamiento_id;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn DescTColumn {
            get {
                return this.columnDescT;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn importeColumn {
            get {
                return this.columnimporte;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn descuentoColumn {
            get {
                return this.columndescuento;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn debeColumn {
            get {
                return this.columndebe;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn haberColumn {
            get {
                return this.columnhaber;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn pecaColumn {
            get {
                return this.columnpeca;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn recibo_idColumn {
            get {
                return this.columnrecibo_id;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn valorrecColumn {
            get {
                return this.columnvalorrec;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn polizaColumn {
            get {
                return this.columnpoliza;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        public int Count {
            get {
                return this.Rows.Count;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VFacturaRow this[int index] {
            get {
                return ((VFacturaRow)(this.Rows[index]));
            }
        }
        
        public event VFacturaRowChangeEventHandler VFacturaRowChanging;
        
        public event VFacturaRowChangeEventHandler VFacturaRowChanged;
        
        public event VFacturaRowChangeEventHandler VFacturaRowDeleting;
        
        public event VFacturaRowChangeEventHandler VFacturaRowDeleted;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void AddVFacturaRow(VFacturaRow row) {
            this.Rows.Add(row);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VFacturaRow AddVFacturaRow(
                    string nhc, 
                    string nombre, 
                    string apellido1, 
                    string apellido2, 
                    string nif, 
                    string cpostal, 
                    string PROV, 
                    string POB, 
                    string DIREC, 
                    string Pais, 
                    string basica_id, 
                    string descripcion, 
                    string direccion, 
                    string poblacion, 
                    string provincia, 
                    string telefono, 
                    string fax, 
                    string postal, 
                    string cif, 
                    string factura_id, 
                    System.DateTime fecha, 
                    string tratamiento_id, 
                    string DescT, 
                    decimal importe, 
                    decimal descuento, 
                    decimal debe, 
                    decimal haber, 
                    string peca, 
                    string recibo_id, 
                    string valorrec, 
                    string poliza) {
            VFacturaRow rowVFacturaRow = ((VFacturaRow)(this.NewRow()));
            object[] columnValuesArray = new object[] {
                    nhc,
                    nombre,
                    apellido1,
                    apellido2,
                    nif,
                    cpostal,
                    PROV,
                    POB,
                    DIREC,
                    Pais,
                    basica_id,
                    descripcion,
                    direccion,
                    poblacion,
                    provincia,
                    telefono,
                    fax,
                    postal,
                    cif,
                    factura_id,
                    fecha,
                    tratamiento_id,
                    DescT,
                    importe,
                    descuento,
                    debe,
                    haber,
                    peca,
                    recibo_id,
                    valorrec,
                    poliza};
            rowVFacturaRow.ItemArray = columnValuesArray;
            this.Rows.Add(rowVFacturaRow);
            return rowVFacturaRow;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataTable Clone() {
            VFacturaDataTable cln = ((VFacturaDataTable)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Data.DataTable CreateInstance() {
            return new VFacturaDataTable();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.columnnhc = base.Columns["nhc"];
            this.columnnombre = base.Columns["nombre"];
            this.columnapellido1 = base.Columns["apellido1"];
            this.columnapellido2 = base.Columns["apellido2"];
            this.columnnif = base.Columns["nif"];
            this.columncpostal = base.Columns["cpostal"];
            this.columnPROV = base.Columns["PROV"];
            this.columnPOB = base.Columns["POB"];
            this.columnDIREC = base.Columns["DIREC"];
            this.columnPais = base.Columns["Pais"];
            this.columnbasica_id = base.Columns["basica_id"];
            this.columndescripcion = base.Columns["descripcion"];
            this.columndireccion = base.Columns["direccion"];
            this.columnpoblacion = base.Columns["poblacion"];
            this.columnprovincia = base.Columns["provincia"];
            this.columntelefono = base.Columns["telefono"];
            this.columnfax = base.Columns["fax"];
            this.columnpostal = base.Columns["postal"];
            this.columncif = base.Columns["cif"];
            this.columnfactura_id = base.Columns["factura_id"];
            this.columnfecha = base.Columns["fecha"];
            this.columntratamiento_id = base.Columns["tratamiento_id"];
            this.columnDescT = base.Columns["DescT"];
            this.columnimporte = base.Columns["importe"];
            this.columndescuento = base.Columns["descuento"];
            this.columndebe = base.Columns["debe"];
            this.columnhaber = base.Columns["haber"];
            this.columnpeca = base.Columns["peca"];
            this.columnrecibo_id = base.Columns["recibo_id"];
            this.columnvalorrec = base.Columns["valorrec"];
            this.columnpoliza = base.Columns["poliza"];
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.columnnhc = new global::System.Data.DataColumn("nhc", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnnhc);
            this.columnnombre = new global::System.Data.DataColumn("nombre", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnnombre);
            this.columnapellido1 = new global::System.Data.DataColumn("apellido1", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnapellido1);
            this.columnapellido2 = new global::System.Data.DataColumn("apellido2", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnapellido2);
            this.columnnif = new global::System.Data.DataColumn("nif", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnnif);
            this.columncpostal = new global::System.Data.DataColumn("cpostal", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columncpostal);
            this.columnPROV = new global::System.Data.DataColumn("PROV", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPROV);
            this.columnPOB = new global::System.Data.DataColumn("POB", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPOB);
            this.columnDIREC = new global::System.Data.DataColumn("DIREC", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnDIREC);
            this.columnPais = new global::System.Data.DataColumn("Pais", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPais);
            this.columnbasica_id = new global::System.Data.DataColumn("basica_id", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnbasica_id);
            this.columndescripcion = new global::System.Data.DataColumn("descripcion", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columndescripcion);
            this.columndireccion = new global::System.Data.DataColumn("direccion", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columndireccion);
            this.columnpoblacion = new global::System.Data.DataColumn("poblacion", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnpoblacion);
            this.columnprovincia = new global::System.Data.DataColumn("provincia", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnprovincia);
            this.columntelefono = new global::System.Data.DataColumn("telefono", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columntelefono);
            this.columnfax = new global::System.Data.DataColumn("fax", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnfax);
            this.columnpostal = new global::System.Data.DataColumn("postal", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnpostal);
            this.columncif = new global::System.Data.DataColumn("cif", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columncif);
            this.columnfactura_id = new global::System.Data.DataColumn("factura_id", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnfactura_id);
            this.columnfecha = new global::System.Data.DataColumn("fecha", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnfecha);
            this.columntratamiento_id = new global::System.Data.DataColumn("tratamiento_id", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columntratamiento_id);
            this.columnDescT = new global::System.Data.DataColumn("DescT", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnDescT);
            this.columnimporte = new global::System.Data.DataColumn("importe", typeof(decimal), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnimporte);
            this.columndescuento = new global::System.Data.DataColumn("descuento", typeof(decimal), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columndescuento);
            this.columndebe = new global::System.Data.DataColumn("debe", typeof(decimal), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columndebe);
            this.columnhaber = new global::System.Data.DataColumn("haber", typeof(decimal), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnhaber);
            this.columnpeca = new global::System.Data.DataColumn("peca", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnpeca);
            this.columnrecibo_id = new global::System.Data.DataColumn("recibo_id", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnrecibo_id);
            this.columnvalorrec = new global::System.Data.DataColumn("valorrec", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnvalorrec);
            this.columnpoliza = new global::System.Data.DataColumn("poliza", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnpoliza);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VFacturaRow NewVFacturaRow() {
            return ((VFacturaRow)(this.NewRow()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
            return new VFacturaRow(builder);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Type GetRowType() {
            return typeof(VFacturaRow);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
            base.OnRowChanged(e);
            if ((this.VFacturaRowChanged != null)) {
                this.VFacturaRowChanged(this, new VFacturaRowChangeEvent(((VFacturaRow)(e.Row)), e.Action));
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
            base.OnRowChanging(e);
            if ((this.VFacturaRowChanging != null)) {
                this.VFacturaRowChanging(this, new VFacturaRowChangeEvent(((VFacturaRow)(e.Row)), e.Action));
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
            base.OnRowDeleted(e);
            if ((this.VFacturaRowDeleted != null)) {
                this.VFacturaRowDeleted(this, new VFacturaRowChangeEvent(((VFacturaRow)(e.Row)), e.Action));
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
            base.OnRowDeleting(e);
            if ((this.VFacturaRowDeleting != null)) {
                this.VFacturaRowDeleting(this, new VFacturaRowChangeEvent(((VFacturaRow)(e.Row)), e.Action));
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void RemoveVFacturaRow(VFacturaRow row) {
            this.Rows.Remove(row);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            Factura ds = new Factura();
            global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
            any1.Namespace = "http://www.w3.org/2001/XMLSchema";
            any1.MinOccurs = new decimal(0);
            any1.MaxOccurs = decimal.MaxValue;
            any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
            sequence.Items.Add(any1);
            global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
            any2.MinOccurs = new decimal(1);
            any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
            sequence.Items.Add(any2);
            global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
            attribute1.Name = "#pragma warning disable 1591

namespace";
            attribute1.FixedValue = ds.Namespace;
            type.Attributes.Add(attribute1);
            global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
            attribute2.Name = "tableTypeName";
            attribute2.FixedValue = "VFacturaDataTable";
            type.Attributes.Add(attribute2);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
    }
    
    /// <summary>
    ///Represents strongly named DataRow class.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    public partial class VFacturaRow : global::System.Data.DataRow {
        
        private VFacturaDataTable tableVFactura;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal VFacturaRow(global::System.Data.DataRowBuilder rb) : 
                base(rb) {
            this.tableVFactura = ((VFacturaDataTable)(this.Table));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string nhc {
            get {
                try {
                    return ((string)(this[this.tableVFactura.nhcColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'nhc\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.nhcColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string nombre {
            get {
                try {
                    return ((string)(this[this.tableVFactura.nombreColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'nombre\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.nombreColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string apellido1 {
            get {
                try {
                    return ((string)(this[this.tableVFactura.apellido1Column]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'apellido1\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.apellido1Column] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string apellido2 {
            get {
                try {
                    return ((string)(this[this.tableVFactura.apellido2Column]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'apellido2\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.apellido2Column] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string nif {
            get {
                try {
                    return ((string)(this[this.tableVFactura.nifColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'nif\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.nifColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string cpostal {
            get {
                try {
                    return ((string)(this[this.tableVFactura.cpostalColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'cpostal\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.cpostalColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PROV {
            get {
                try {
                    return ((string)(this[this.tableVFactura.PROVColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'PROV\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.PROVColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string POB {
            get {
                try {
                    return ((string)(this[this.tableVFactura.POBColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'POB\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.POBColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DIREC {
            get {
                try {
                    return ((string)(this[this.tableVFactura.DIRECColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'DIREC\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.DIRECColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Pais {
            get {
                try {
                    return ((string)(this[this.tableVFactura.PaisColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'Pais\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.PaisColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string basica_id {
            get {
                try {
                    return ((string)(this[this.tableVFactura.basica_idColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'basica_id\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.basica_idColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string descripcion {
            get {
                try {
                    return ((string)(this[this.tableVFactura.descripcionColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'descripcion\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.descripcionColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string direccion {
            get {
                try {
                    return ((string)(this[this.tableVFactura.direccionColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'direccion\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.direccionColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string poblacion {
            get {
                try {
                    return ((string)(this[this.tableVFactura.poblacionColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'poblacion\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.poblacionColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string provincia {
            get {
                try {
                    return ((string)(this[this.tableVFactura.provinciaColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'provincia\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.provinciaColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string telefono {
            get {
                try {
                    return ((string)(this[this.tableVFactura.telefonoColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'telefono\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.telefonoColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string fax {
            get {
                try {
                    return ((string)(this[this.tableVFactura.faxColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'fax\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.faxColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string postal {
            get {
                try {
                    return ((string)(this[this.tableVFactura.postalColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'postal\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.postalColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string cif {
            get {
                try {
                    return ((string)(this[this.tableVFactura.cifColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'cif\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.cifColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string factura_id {
            get {
                try {
                    return ((string)(this[this.tableVFactura.factura_idColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'factura_id\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.factura_idColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public System.DateTime fecha {
            get {
                try {
                    return ((global::System.DateTime)(this[this.tableVFactura.fechaColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'fecha\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.fechaColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string tratamiento_id {
            get {
                try {
                    return ((string)(this[this.tableVFactura.tratamiento_idColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'tratamiento_id\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.tratamiento_idColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DescT {
            get {
                try {
                    return ((string)(this[this.tableVFactura.DescTColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'DescT\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.DescTColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal importe {
            get {
                try {
                    return ((decimal)(this[this.tableVFactura.importeColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'importe\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.importeColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal descuento {
            get {
                try {
                    return ((decimal)(this[this.tableVFactura.descuentoColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'descuento\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.descuentoColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal debe {
            get {
                try {
                    return ((decimal)(this[this.tableVFactura.debeColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'debe\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.debeColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal haber {
            get {
                try {
                    return ((decimal)(this[this.tableVFactura.haberColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'haber\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.haberColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string peca {
            get {
                try {
                    return ((string)(this[this.tableVFactura.pecaColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'peca\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.pecaColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string recibo_id {
            get {
                try {
                    return ((string)(this[this.tableVFactura.recibo_idColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'recibo_id\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.recibo_idColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string valorrec {
            get {
                try {
                    return ((string)(this[this.tableVFactura.valorrecColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'valorrec\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.valorrecColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string poliza {
            get {
                try {
                    return ((string)(this[this.tableVFactura.polizaColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'poliza\' in table \'VFactura\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVFactura.polizaColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsnhcNull() {
            return this.IsNull(this.tableVFactura.nhcColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetnhcNull() {
            this[this.tableVFactura.nhcColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsnombreNull() {
            return this.IsNull(this.tableVFactura.nombreColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetnombreNull() {
            this[this.tableVFactura.nombreColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Isapellido1Null() {
            return this.IsNull(this.tableVFactura.apellido1Column);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Setapellido1Null() {
            this[this.tableVFactura.apellido1Column] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Isapellido2Null() {
            return this.IsNull(this.tableVFactura.apellido2Column);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Setapellido2Null() {
            this[this.tableVFactura.apellido2Column] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsnifNull() {
            return this.IsNull(this.tableVFactura.nifColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetnifNull() {
            this[this.tableVFactura.nifColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IscpostalNull() {
            return this.IsNull(this.tableVFactura.cpostalColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetcpostalNull() {
            this[this.tableVFactura.cpostalColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsPROVNull() {
            return this.IsNull(this.tableVFactura.PROVColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetPROVNull() {
            this[this.tableVFactura.PROVColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsPOBNull() {
            return this.IsNull(this.tableVFactura.POBColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetPOBNull() {
            this[this.tableVFactura.POBColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsDIRECNull() {
            return this.IsNull(this.tableVFactura.DIRECColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetDIRECNull() {
            this[this.tableVFactura.DIRECColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsPaisNull() {
            return this.IsNull(this.tableVFactura.PaisColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetPaisNull() {
            this[this.tableVFactura.PaisColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Isbasica_idNull() {
            return this.IsNull(this.tableVFactura.basica_idColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Setbasica_idNull() {
            this[this.tableVFactura.basica_idColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsdescripcionNull() {
            return this.IsNull(this.tableVFactura.descripcionColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetdescripcionNull() {
            this[this.tableVFactura.descripcionColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsdireccionNull() {
            return this.IsNull(this.tableVFactura.direccionColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetdireccionNull() {
            this[this.tableVFactura.direccionColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IspoblacionNull() {
            return this.IsNull(this.tableVFactura.poblacionColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetpoblacionNull() {
            this[this.tableVFactura.poblacionColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsprovinciaNull() {
            return this.IsNull(this.tableVFactura.provinciaColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetprovinciaNull() {
            this[this.tableVFactura.provinciaColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IstelefonoNull() {
            return this.IsNull(this.tableVFactura.telefonoColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SettelefonoNull() {
            this[this.tableVFactura.telefonoColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsfaxNull() {
            return this.IsNull(this.tableVFactura.faxColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetfaxNull() {
            this[this.tableVFactura.faxColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IspostalNull() {
            return this.IsNull(this.tableVFactura.postalColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetpostalNull() {
            this[this.tableVFactura.postalColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IscifNull() {
            return this.IsNull(this.tableVFactura.cifColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetcifNull() {
            this[this.tableVFactura.cifColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Isfactura_idNull() {
            return this.IsNull(this.tableVFactura.factura_idColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Setfactura_idNull() {
            this[this.tableVFactura.factura_idColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsfechaNull() {
            return this.IsNull(this.tableVFactura.fechaColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetfechaNull() {
            this[this.tableVFactura.fechaColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Istratamiento_idNull() {
            return this.IsNull(this.tableVFactura.tratamiento_idColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Settratamiento_idNull() {
            this[this.tableVFactura.tratamiento_idColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsDescTNull() {
            return this.IsNull(this.tableVFactura.DescTColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetDescTNull() {
            this[this.tableVFactura.DescTColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsimporteNull() {
            return this.IsNull(this.tableVFactura.importeColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetimporteNull() {
            this[this.tableVFactura.importeColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsdescuentoNull() {
            return this.IsNull(this.tableVFactura.descuentoColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetdescuentoNull() {
            this[this.tableVFactura.descuentoColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsdebeNull() {
            return this.IsNull(this.tableVFactura.debeColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetdebeNull() {
            this[this.tableVFactura.debeColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IshaberNull() {
            return this.IsNull(this.tableVFactura.haberColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SethaberNull() {
            this[this.tableVFactura.haberColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IspecaNull() {
            return this.IsNull(this.tableVFactura.pecaColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetpecaNull() {
            this[this.tableVFactura.pecaColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Isrecibo_idNull() {
            return this.IsNull(this.tableVFactura.recibo_idColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Setrecibo_idNull() {
            this[this.tableVFactura.recibo_idColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsvalorrecNull() {
            return this.IsNull(this.tableVFactura.valorrecColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetvalorrecNull() {
            this[this.tableVFactura.valorrecColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IspolizaNull() {
            return this.IsNull(this.tableVFactura.polizaColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetpolizaNull() {
            this[this.tableVFactura.polizaColumn] = global::System.Convert.DBNull;
        }
    }
    
    /// <summary>
    ///Row event argument class
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    public class VFacturaRowChangeEvent : global::System.EventArgs {
        
        private VFacturaRow eventRow;
        
        private global::System.Data.DataRowAction eventAction;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VFacturaRowChangeEvent(VFacturaRow row, global::System.Data.DataRowAction action) {
            this.eventRow = row;
            this.eventAction = action;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VFacturaRow Row {
            get {
                return this.eventRow;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataRowAction Action {
            get {
                return this.eventAction;
            }
        }
    }
}

#pragma warning restore 1591