//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
///Represents a strongly typed in-memory cache of data.
///</summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
[global::System.Serializable()]
[global::System.ComponentModel.DesignerCategoryAttribute("code")]
[global::System.ComponentModel.ToolboxItem(true)]
[global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
[global::System.Xml.Serialization.XmlRootAttribute("Vpagos")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
public partial class Vpagos : global::System.Data.DataSet {
    
    private VpagosDataTable tableVpagos;
    
    private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public Vpagos() {
        this.BeginInit();
        this.InitClass();
        global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
        base.Tables.CollectionChanged += schemaChangedHandler;
        base.Relations.CollectionChanged += schemaChangedHandler;
        this.EndInit();
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    protected Vpagos(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
            base(info, context, false) {
        if ((this.IsBinarySerialized(info, context) == true)) {
            this.InitVars(false);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler1;
            this.Relations.CollectionChanged += schemaChangedHandler1;
            return;
        }
        string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
        if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
            global::System.Data.DataSet ds = new global::System.Data.DataSet();
            ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            if ((ds.Tables["Vpagos"] != null)) {
                base.Tables.Add(new VpagosDataTable(ds.Tables["Vpagos"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        else {
            this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
        }
        this.GetSerializationData(info, context);
        global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
        base.Tables.CollectionChanged += schemaChangedHandler;
        this.Relations.CollectionChanged += schemaChangedHandler;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.Browsable(false)]
    [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
    public VpagosDataTable _Vpagos {
        get {
            return this.tableVpagos;
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.BrowsableAttribute(true)]
    [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
    public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
        get {
            return this._schemaSerializationMode;
        }
        set {
            this._schemaSerializationMode = value;
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public new global::System.Data.DataTableCollection Tables {
        get {
            return base.Tables;
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public new global::System.Data.DataRelationCollection Relations {
        get {
            return base.Relations;
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    protected override void InitializeDerivedDataSet() {
        this.BeginInit();
        this.InitClass();
        this.EndInit();
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public override global::System.Data.DataSet Clone() {
        Vpagos cln = ((Vpagos)(base.Clone()));
        cln.InitVars();
        cln.SchemaSerializationMode = this.SchemaSerializationMode;
        return cln;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    protected override bool ShouldSerializeTables() {
        return false;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    protected override bool ShouldSerializeRelations() {
        return false;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
        if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
            this.Reset();
            global::System.Data.DataSet ds = new global::System.Data.DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Vpagos"] != null)) {
                base.Tables.Add(new VpagosDataTable(ds.Tables["Vpagos"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        else {
            this.ReadXml(reader);
            this.InitVars();
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
        global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
        this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
        stream.Position = 0;
        return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal void InitVars() {
        this.InitVars(true);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal void InitVars(bool initTable) {
        this.tableVpagos = ((VpagosDataTable)(base.Tables["Vpagos"]));
        if ((initTable == true)) {
            if ((this.tableVpagos != null)) {
                this.tableVpagos.InitVars();
            }
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    private void InitClass() {
        this.DataSetName = "Vpagos";
        this.Prefix = "";
        this.Namespace = "http://tempuri.org/Vpagos.xsd";
        this.EnforceConstraints = true;
        this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        this.tableVpagos = new VpagosDataTable();
        base.Tables.Add(this.tableVpagos);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    private bool ShouldSerialize_Vpagos() {
        return false;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
        if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
            this.InitVars();
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
        Vpagos ds = new Vpagos();
        global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
        global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
        global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
        any.Namespace = ds.Namespace;
        sequence.Items.Add(any);
        type.Particle = sequence;
        global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
        if (xs.Contains(dsSchema.TargetNamespace)) {
            global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
            global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
            try {
                global::System.Xml.Schema.XmlSchema schema = null;
                dsSchema.Write(s1);
                for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                    schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                    s2.SetLength(0);
                    schema.Write(s2);
                    if ((s1.Length == s2.Length)) {
                        s1.Position = 0;
                        s2.Position = 0;
                        for (; ((s1.Position != s1.Length) 
                                    && (s1.ReadByte() == s2.ReadByte())); ) {
                            ;
                        }
                        if ((s1.Position == s1.Length)) {
                            return type;
                        }
                    }
                }
            }
            finally {
                if ((s1 != null)) {
                    s1.Close();
                }
                if ((s2 != null)) {
                    s2.Close();
                }
            }
        }
        xs.Add(dsSchema);
        return type;
    }
    
    public delegate void VpagosRowChangeEventHandler(object sender, VpagosRowChangeEvent e);
    
    /// <summary>
    ///Represents the strongly named DataTable class.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
    public partial class VpagosDataTable : global::System.Data.TypedTableBase<VpagosRow> {
        
        private global::System.Data.DataColumn columnnhc;
        
        private global::System.Data.DataColumn columnnombre;
        
        private global::System.Data.DataColumn columnapellido1;
        
        private global::System.Data.DataColumn columnapellido2;
        
        private global::System.Data.DataColumn columnnif;
        
        private global::System.Data.DataColumn columncpostal;
        
        private global::System.Data.DataColumn columnPROV;
        
        private global::System.Data.DataColumn columnPOB;
        
        private global::System.Data.DataColumn columnDIREC;
        
        private global::System.Data.DataColumn columnPais;
        
        private global::System.Data.DataColumn columnrecibo_id;
        
        private global::System.Data.DataColumn columndescripcion;
        
        private global::System.Data.DataColumn columndireccion;
        
        private global::System.Data.DataColumn columnpoblacion;
        
        private global::System.Data.DataColumn columnprovincia;
        
        private global::System.Data.DataColumn columntelefono;
        
        private global::System.Data.DataColumn columnfax;
        
        private global::System.Data.DataColumn columnpostal;
        
        private global::System.Data.DataColumn columncif;
        
        private global::System.Data.DataColumn columnfecha;
        
        private global::System.Data.DataColumn columntipo;
        
        private global::System.Data.DataColumn columnimporte;
        
        private global::System.Data.DataColumn columnMoedaFracção;
        
        private global::System.Data.DataColumn columnMoedaNome;
        
        private global::System.Data.DataColumn columnpoliza;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VpagosDataTable() {
            this.TableName = "Vpagos";
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal VpagosDataTable(global::System.Data.DataTable table) {
            this.TableName = table.TableName;
            if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                this.CaseSensitive = table.CaseSensitive;
            }
            if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                this.Locale = table.Locale;
            }
            if ((table.Namespace != table.DataSet.Namespace)) {
                this.Namespace = table.Namespace;
            }
            this.Prefix = table.Prefix;
            this.MinimumCapacity = table.MinimumCapacity;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected VpagosDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context) {
            this.InitVars();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn nhcColumn {
            get {
                return this.columnnhc;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn nombreColumn {
            get {
                return this.columnnombre;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn apellido1Column {
            get {
                return this.columnapellido1;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn apellido2Column {
            get {
                return this.columnapellido2;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn nifColumn {
            get {
                return this.columnnif;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn cpostalColumn {
            get {
                return this.columncpostal;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn PROVColumn {
            get {
                return this.columnPROV;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn POBColumn {
            get {
                return this.columnPOB;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn DIRECColumn {
            get {
                return this.columnDIREC;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn PaisColumn {
            get {
                return this.columnPais;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn recibo_idColumn {
            get {
                return this.columnrecibo_id;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn descripcionColumn {
            get {
                return this.columndescripcion;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn direccionColumn {
            get {
                return this.columndireccion;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn poblacionColumn {
            get {
                return this.columnpoblacion;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn provinciaColumn {
            get {
                return this.columnprovincia;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn telefonoColumn {
            get {
                return this.columntelefono;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn faxColumn {
            get {
                return this.columnfax;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn postalColumn {
            get {
                return this.columnpostal;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn cifColumn {
            get {
                return this.columncif;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn fechaColumn {
            get {
                return this.columnfecha;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn tipoColumn {
            get {
                return this.columntipo;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn importeColumn {
            get {
                return this.columnimporte;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn MoedaFracçãoColumn {
            get {
                return this.columnMoedaFracção;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn MoedaNomeColumn {
            get {
                return this.columnMoedaNome;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataColumn polizaColumn {
            get {
                return this.columnpoliza;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        public int Count {
            get {
                return this.Rows.Count;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VpagosRow this[int index] {
            get {
                return ((VpagosRow)(this.Rows[index]));
            }
        }
        
        public event VpagosRowChangeEventHandler VpagosRowChanging;
        
        public event VpagosRowChangeEventHandler VpagosRowChanged;
        
        public event VpagosRowChangeEventHandler VpagosRowDeleting;
        
        public event VpagosRowChangeEventHandler VpagosRowDeleted;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void AddVpagosRow(VpagosRow row) {
            this.Rows.Add(row);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VpagosRow AddVpagosRow(
                    string nhc, 
                    string nombre, 
                    string apellido1, 
                    string apellido2, 
                    string nif, 
                    string cpostal, 
                    string PROV, 
                    string POB, 
                    string DIREC, 
                    string Pais, 
                    string recibo_id, 
                    string descripcion, 
                    string direccion, 
                    string poblacion, 
                    string provincia, 
                    string telefono, 
                    string fax, 
                    string postal, 
                    string cif, 
                    System.DateTime fecha, 
                    string tipo, 
                    decimal importe, 
                    decimal MoedaFracção, 
                    decimal MoedaNome, 
                    string poliza) {
            VpagosRow rowVpagosRow = ((VpagosRow)(this.NewRow()));
            object[] columnValuesArray = new object[] {
                    nhc,
                    nombre,
                    apellido1,
                    apellido2,
                    nif,
                    cpostal,
                    PROV,
                    POB,
                    DIREC,
                    Pais,
                    recibo_id,
                    descripcion,
                    direccion,
                    poblacion,
                    provincia,
                    telefono,
                    fax,
                    postal,
                    cif,
                    fecha,
                    tipo,
                    importe,
                    MoedaFracção,
                    MoedaNome,
                    poliza};
            rowVpagosRow.ItemArray = columnValuesArray;
            this.Rows.Add(rowVpagosRow);
            return rowVpagosRow;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataTable Clone() {
            VpagosDataTable cln = ((VpagosDataTable)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Data.DataTable CreateInstance() {
            return new VpagosDataTable();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.columnnhc = base.Columns["nhc"];
            this.columnnombre = base.Columns["nombre"];
            this.columnapellido1 = base.Columns["apellido1"];
            this.columnapellido2 = base.Columns["apellido2"];
            this.columnnif = base.Columns["nif"];
            this.columncpostal = base.Columns["cpostal"];
            this.columnPROV = base.Columns["PROV"];
            this.columnPOB = base.Columns["POB"];
            this.columnDIREC = base.Columns["DIREC"];
            this.columnPais = base.Columns["Pais"];
            this.columnrecibo_id = base.Columns["recibo_id"];
            this.columndescripcion = base.Columns["descripcion"];
            this.columndireccion = base.Columns["direccion"];
            this.columnpoblacion = base.Columns["poblacion"];
            this.columnprovincia = base.Columns["provincia"];
            this.columntelefono = base.Columns["telefono"];
            this.columnfax = base.Columns["fax"];
            this.columnpostal = base.Columns["postal"];
            this.columncif = base.Columns["cif"];
            this.columnfecha = base.Columns["fecha"];
            this.columntipo = base.Columns["tipo"];
            this.columnimporte = base.Columns["importe"];
            this.columnMoedaFracção = base.Columns["MoedaFracção"];
            this.columnMoedaNome = base.Columns["MoedaNome"];
            this.columnpoliza = base.Columns["poliza"];
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.columnnhc = new global::System.Data.DataColumn("nhc", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnnhc);
            this.columnnombre = new global::System.Data.DataColumn("nombre", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnnombre);
            this.columnapellido1 = new global::System.Data.DataColumn("apellido1", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnapellido1);
            this.columnapellido2 = new global::System.Data.DataColumn("apellido2", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnapellido2);
            this.columnnif = new global::System.Data.DataColumn("nif", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnnif);
            this.columncpostal = new global::System.Data.DataColumn("cpostal", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columncpostal);
            this.columnPROV = new global::System.Data.DataColumn("PROV", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPROV);
            this.columnPOB = new global::System.Data.DataColumn("POB", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPOB);
            this.columnDIREC = new global::System.Data.DataColumn("DIREC", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnDIREC);
            this.columnPais = new global::System.Data.DataColumn("Pais", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPais);
            this.columnrecibo_id = new global::System.Data.DataColumn("recibo_id", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnrecibo_id);
            this.columndescripcion = new global::System.Data.DataColumn("descripcion", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columndescripcion);
            this.columndireccion = new global::System.Data.DataColumn("direccion", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columndireccion);
            this.columnpoblacion = new global::System.Data.DataColumn("poblacion", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnpoblacion);
            this.columnprovincia = new global::System.Data.DataColumn("provincia", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnprovincia);
            this.columntelefono = new global::System.Data.DataColumn("telefono", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columntelefono);
            this.columnfax = new global::System.Data.DataColumn("fax", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnfax);
            this.columnpostal = new global::System.Data.DataColumn("postal", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnpostal);
            this.columncif = new global::System.Data.DataColumn("cif", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columncif);
            this.columnfecha = new global::System.Data.DataColumn("fecha", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnfecha);
            this.columntipo = new global::System.Data.DataColumn("tipo", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columntipo);
            this.columnimporte = new global::System.Data.DataColumn("importe", typeof(decimal), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnimporte);
            this.columnMoedaFracção = new global::System.Data.DataColumn("MoedaFracção", typeof(decimal), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnMoedaFracção);
            this.columnMoedaNome = new global::System.Data.DataColumn("MoedaNome", typeof(decimal), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnMoedaNome);
            this.columnpoliza = new global::System.Data.DataColumn("poliza", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnpoliza);
            this.columnrecibo_id.Caption = "basica_id";
            this.columntipo.Caption = "tratamiento_id";
            this.columnMoedaFracção.Caption = "descuento";
            this.columnMoedaNome.Caption = "debe";
            this.ExtendedProperties.Add("Generator_TablePropName", "_Vpagos");
            this.ExtendedProperties.Add("Generator_UserTableName", "Vpagos");
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VpagosRow NewVpagosRow() {
            return ((VpagosRow)(this.NewRow()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
            return new VpagosRow(builder);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Type GetRowType() {
            return typeof(VpagosRow);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
            base.OnRowChanged(e);
            if ((this.VpagosRowChanged != null)) {
                this.VpagosRowChanged(this, new VpagosRowChangeEvent(((VpagosRow)(e.Row)), e.Action));
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
            base.OnRowChanging(e);
            if ((this.VpagosRowChanging != null)) {
                this.VpagosRowChanging(this, new VpagosRowChangeEvent(((VpagosRow)(e.Row)), e.Action));
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
            base.OnRowDeleted(e);
            if ((this.VpagosRowDeleted != null)) {
                this.VpagosRowDeleted(this, new VpagosRowChangeEvent(((VpagosRow)(e.Row)), e.Action));
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
            base.OnRowDeleting(e);
            if ((this.VpagosRowDeleting != null)) {
                this.VpagosRowDeleting(this, new VpagosRowChangeEvent(((VpagosRow)(e.Row)), e.Action));
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void RemoveVpagosRow(VpagosRow row) {
            this.Rows.Remove(row);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            Vpagos ds = new Vpagos();
            global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
            any1.Namespace = "http://www.w3.org/2001/XMLSchema";
            any1.MinOccurs = new decimal(0);
            any1.MaxOccurs = decimal.MaxValue;
            any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
            sequence.Items.Add(any1);
            global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
            any2.MinOccurs = new decimal(1);
            any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
            sequence.Items.Add(any2);
            global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
            attribute1.Name = "#pragma warning disable 1591

namespace";
            attribute1.FixedValue = ds.Namespace;
            type.Attributes.Add(attribute1);
            global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
            attribute2.Name = "tableTypeName";
            attribute2.FixedValue = "VpagosDataTable";
            type.Attributes.Add(attribute2);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
    }
    
    /// <summary>
    ///Represents strongly named DataRow class.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    public partial class VpagosRow : global::System.Data.DataRow {
        
        private VpagosDataTable tableVpagos;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal VpagosRow(global::System.Data.DataRowBuilder rb) : 
                base(rb) {
            this.tableVpagos = ((VpagosDataTable)(this.Table));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string nhc {
            get {
                try {
                    return ((string)(this[this.tableVpagos.nhcColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'nhc\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.nhcColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string nombre {
            get {
                try {
                    return ((string)(this[this.tableVpagos.nombreColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'nombre\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.nombreColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string apellido1 {
            get {
                try {
                    return ((string)(this[this.tableVpagos.apellido1Column]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'apellido1\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.apellido1Column] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string apellido2 {
            get {
                try {
                    return ((string)(this[this.tableVpagos.apellido2Column]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'apellido2\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.apellido2Column] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string nif {
            get {
                try {
                    return ((string)(this[this.tableVpagos.nifColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'nif\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.nifColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string cpostal {
            get {
                try {
                    return ((string)(this[this.tableVpagos.cpostalColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'cpostal\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.cpostalColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PROV {
            get {
                try {
                    return ((string)(this[this.tableVpagos.PROVColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'PROV\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.PROVColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string POB {
            get {
                try {
                    return ((string)(this[this.tableVpagos.POBColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'POB\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.POBColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DIREC {
            get {
                try {
                    return ((string)(this[this.tableVpagos.DIRECColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'DIREC\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.DIRECColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Pais {
            get {
                try {
                    return ((string)(this[this.tableVpagos.PaisColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'Pais\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.PaisColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string recibo_id {
            get {
                try {
                    return ((string)(this[this.tableVpagos.recibo_idColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'recibo_id\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.recibo_idColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string descripcion {
            get {
                try {
                    return ((string)(this[this.tableVpagos.descripcionColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'descripcion\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.descripcionColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string direccion {
            get {
                try {
                    return ((string)(this[this.tableVpagos.direccionColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'direccion\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.direccionColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string poblacion {
            get {
                try {
                    return ((string)(this[this.tableVpagos.poblacionColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'poblacion\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.poblacionColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string provincia {
            get {
                try {
                    return ((string)(this[this.tableVpagos.provinciaColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'provincia\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.provinciaColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string telefono {
            get {
                try {
                    return ((string)(this[this.tableVpagos.telefonoColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'telefono\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.telefonoColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string fax {
            get {
                try {
                    return ((string)(this[this.tableVpagos.faxColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'fax\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.faxColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string postal {
            get {
                try {
                    return ((string)(this[this.tableVpagos.postalColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'postal\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.postalColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string cif {
            get {
                try {
                    return ((string)(this[this.tableVpagos.cifColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'cif\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.cifColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public System.DateTime fecha {
            get {
                try {
                    return ((global::System.DateTime)(this[this.tableVpagos.fechaColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'fecha\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.fechaColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string tipo {
            get {
                try {
                    return ((string)(this[this.tableVpagos.tipoColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'tipo\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.tipoColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal importe {
            get {
                try {
                    return ((decimal)(this[this.tableVpagos.importeColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'importe\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.importeColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal MoedaFracção {
            get {
                try {
                    return ((decimal)(this[this.tableVpagos.MoedaFracçãoColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'MoedaFracção\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.MoedaFracçãoColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal MoedaNome {
            get {
                try {
                    return ((decimal)(this[this.tableVpagos.MoedaNomeColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'MoedaNome\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.MoedaNomeColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string poliza {
            get {
                try {
                    return ((string)(this[this.tableVpagos.polizaColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'poliza\' in table \'Vpagos\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVpagos.polizaColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsnhcNull() {
            return this.IsNull(this.tableVpagos.nhcColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetnhcNull() {
            this[this.tableVpagos.nhcColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsnombreNull() {
            return this.IsNull(this.tableVpagos.nombreColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetnombreNull() {
            this[this.tableVpagos.nombreColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Isapellido1Null() {
            return this.IsNull(this.tableVpagos.apellido1Column);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Setapellido1Null() {
            this[this.tableVpagos.apellido1Column] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Isapellido2Null() {
            return this.IsNull(this.tableVpagos.apellido2Column);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Setapellido2Null() {
            this[this.tableVpagos.apellido2Column] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsnifNull() {
            return this.IsNull(this.tableVpagos.nifColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetnifNull() {
            this[this.tableVpagos.nifColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IscpostalNull() {
            return this.IsNull(this.tableVpagos.cpostalColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetcpostalNull() {
            this[this.tableVpagos.cpostalColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsPROVNull() {
            return this.IsNull(this.tableVpagos.PROVColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetPROVNull() {
            this[this.tableVpagos.PROVColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsPOBNull() {
            return this.IsNull(this.tableVpagos.POBColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetPOBNull() {
            this[this.tableVpagos.POBColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsDIRECNull() {
            return this.IsNull(this.tableVpagos.DIRECColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetDIRECNull() {
            this[this.tableVpagos.DIRECColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsPaisNull() {
            return this.IsNull(this.tableVpagos.PaisColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetPaisNull() {
            this[this.tableVpagos.PaisColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Isrecibo_idNull() {
            return this.IsNull(this.tableVpagos.recibo_idColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Setrecibo_idNull() {
            this[this.tableVpagos.recibo_idColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsdescripcionNull() {
            return this.IsNull(this.tableVpagos.descripcionColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetdescripcionNull() {
            this[this.tableVpagos.descripcionColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsdireccionNull() {
            return this.IsNull(this.tableVpagos.direccionColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetdireccionNull() {
            this[this.tableVpagos.direccionColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IspoblacionNull() {
            return this.IsNull(this.tableVpagos.poblacionColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetpoblacionNull() {
            this[this.tableVpagos.poblacionColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsprovinciaNull() {
            return this.IsNull(this.tableVpagos.provinciaColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetprovinciaNull() {
            this[this.tableVpagos.provinciaColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IstelefonoNull() {
            return this.IsNull(this.tableVpagos.telefonoColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SettelefonoNull() {
            this[this.tableVpagos.telefonoColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsfaxNull() {
            return this.IsNull(this.tableVpagos.faxColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetfaxNull() {
            this[this.tableVpagos.faxColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IspostalNull() {
            return this.IsNull(this.tableVpagos.postalColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetpostalNull() {
            this[this.tableVpagos.postalColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IscifNull() {
            return this.IsNull(this.tableVpagos.cifColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetcifNull() {
            this[this.tableVpagos.cifColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsfechaNull() {
            return this.IsNull(this.tableVpagos.fechaColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetfechaNull() {
            this[this.tableVpagos.fechaColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IstipoNull() {
            return this.IsNull(this.tableVpagos.tipoColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SettipoNull() {
            this[this.tableVpagos.tipoColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsimporteNull() {
            return this.IsNull(this.tableVpagos.importeColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetimporteNull() {
            this[this.tableVpagos.importeColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsMoedaFracçãoNull() {
            return this.IsNull(this.tableVpagos.MoedaFracçãoColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetMoedaFracçãoNull() {
            this[this.tableVpagos.MoedaFracçãoColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsMoedaNomeNull() {
            return this.IsNull(this.tableVpagos.MoedaNomeColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetMoedaNomeNull() {
            this[this.tableVpagos.MoedaNomeColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IspolizaNull() {
            return this.IsNull(this.tableVpagos.polizaColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void SetpolizaNull() {
            this[this.tableVpagos.polizaColumn] = global::System.Convert.DBNull;
        }
    }
    
    /// <summary>
    ///Row event argument class
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    public class VpagosRowChangeEvent : global::System.EventArgs {
        
        private VpagosRow eventRow;
        
        private global::System.Data.DataRowAction eventAction;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VpagosRowChangeEvent(VpagosRow row, global::System.Data.DataRowAction action) {
            this.eventRow = row;
            this.eventAction = action;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VpagosRow Row {
            get {
                return this.eventRow;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataRowAction Action {
            get {
                return this.eventAction;
            }
        }
    }
}

#pragma warning restore 1591