//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class AuditFile {
    
    private Header headerField;
    
    private object[] masterFilesField;
    
    private GeneralLedgerEntries generalLedgerEntriesField;
    
    private SourceDocuments sourceDocumentsField;
    
    /// <remarks/>
    public Header Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Customer", typeof(Customer), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("GeneralLedger", typeof(GeneralLedger), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Product", typeof(Product), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Supplier", typeof(Supplier), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("TaxTable", typeof(TaxTable), IsNullable=false)]
    public object[] MasterFiles {
        get {
            return this.masterFilesField;
        }
        set {
            this.masterFilesField = value;
        }
    }
    
    /// <remarks/>
    public GeneralLedgerEntries GeneralLedgerEntries {
        get {
            return this.generalLedgerEntriesField;
        }
        set {
            this.generalLedgerEntriesField = value;
        }
    }
    
    /// <remarks/>
    public SourceDocuments SourceDocuments {
        get {
            return this.sourceDocumentsField;
        }
        set {
            this.sourceDocumentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class Header {
    
    private string auditFileVersionField;
    
    private string companyIDField;
    
    private string taxRegistrationNumberField;
    
    private TaxAccountingBasis taxAccountingBasisField;
    
    private string companyNameField;
    
    private string businessNameField;
    
    private AddressStructurePT companyAddressField;
    
    private string fiscalYearField;
    
    private System.DateTime startDateField;
    
    private System.DateTime endDateField;
    
    private string currencyCodeField;
    
    private System.DateTime dateCreatedField;
    
    private string taxEntityField;
    
    private string productCompanyTaxIDField;
    
    private string softwareCertificateNumberField;
    
    private string productIDField;
    
    private string productVersionField;
    
    private string headerCommentField;
    
    private string telephoneField;
    
    private string faxField;
    
    private string emailField;
    
    private string websiteField;
    
    /// <remarks/>
    public string AuditFileVersion {
        get {
            return this.auditFileVersionField;
        }
        set {
            this.auditFileVersionField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyID {
        get {
            return this.companyIDField;
        }
        set {
            this.companyIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TaxRegistrationNumber {
        get {
            return this.taxRegistrationNumberField;
        }
        set {
            this.taxRegistrationNumberField = value;
        }
    }
    
    /// <remarks/>
    public TaxAccountingBasis TaxAccountingBasis {
        get {
            return this.taxAccountingBasisField;
        }
        set {
            this.taxAccountingBasisField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public string BusinessName {
        get {
            return this.businessNameField;
        }
        set {
            this.businessNameField = value;
        }
    }
    
    /// <remarks/>
    public AddressStructurePT CompanyAddress {
        get {
            return this.companyAddressField;
        }
        set {
            this.companyAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string FiscalYear {
        get {
            return this.fiscalYearField;
        }
        set {
            this.fiscalYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime StartDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    public string CurrencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <remarks/>
    public string TaxEntity {
        get {
            return this.taxEntityField;
        }
        set {
            this.taxEntityField = value;
        }
    }
    
    /// <remarks/>
    public string ProductCompanyTaxID {
        get {
            return this.productCompanyTaxIDField;
        }
        set {
            this.productCompanyTaxIDField = value;
        }
    }
    
    /// <remarks/>
    public string SoftwareCertificateNumber {
        get {
            return this.softwareCertificateNumberField;
        }
        set {
            this.softwareCertificateNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ProductID {
        get {
            return this.productIDField;
        }
        set {
            this.productIDField = value;
        }
    }
    
    /// <remarks/>
    public string ProductVersion {
        get {
            return this.productVersionField;
        }
        set {
            this.productVersionField = value;
        }
    }
    
    /// <remarks/>
    public string HeaderComment {
        get {
            return this.headerCommentField;
        }
        set {
            this.headerCommentField = value;
        }
    }
    
    /// <remarks/>
    public string Telephone {
        get {
            return this.telephoneField;
        }
        set {
            this.telephoneField = value;
        }
    }
    
    /// <remarks/>
    public string Fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string Website {
        get {
            return this.websiteField;
        }
        set {
            this.websiteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public enum TaxAccountingBasis {
    
    /// <remarks/>
    C,
    
    /// <remarks/>
    F,
    
    /// <remarks/>
    I,
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    P,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute("CompanyAddress", Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class AddressStructurePT {
    
    private string buildingNumberField;
    
    private string streetNameField;
    
    private string addressDetailField;
    
    private string cityField;
    
    private string postalCodeField;
    
    private string regionField;
    
    private object countryField;
    
    /// <remarks/>
    public string BuildingNumber {
        get {
            return this.buildingNumberField;
        }
        set {
            this.buildingNumberField = value;
        }
    }
    
    /// <remarks/>
    public string StreetName {
        get {
            return this.streetNameField;
        }
        set {
            this.streetNameField = value;
        }
    }
    
    /// <remarks/>
    public string AddressDetail {
        get {
            return this.addressDetailField;
        }
        set {
            this.addressDetailField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='PT' attribute.
    public object Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
public partial class SupplierAddressStructure {
    
    private string buildingNumberField;
    
    private string streetNameField;
    
    private string addressDetailField;
    
    private string cityField;
    
    private string postalCodeField;
    
    private string regionField;
    
    private string countryField;
    
    /// <remarks/>
    public string BuildingNumber {
        get {
            return this.buildingNumberField;
        }
        set {
            this.buildingNumberField = value;
        }
    }
    
    /// <remarks/>
    public string StreetName {
        get {
            return this.streetNameField;
        }
        set {
            this.streetNameField = value;
        }
    }
    
    /// <remarks/>
    public string AddressDetail {
        get {
            return this.addressDetailField;
        }
        set {
            this.addressDetailField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class Customer {
    
    private string customerIDField;
    
    private string accountIDField;
    
    private string customerTaxIDField;
    
    private string companyNameField;
    
    private string contactField;
    
    private AddressStructure billingAddressField;
    
    private AddressStructure shipToAddressField;
    
    private string telephoneField;
    
    private string faxField;
    
    private string emailField;
    
    private string websiteField;
    
    private string selfBillingIndicatorField;
    
    /// <remarks/>
    public string CustomerID {
        get {
            return this.customerIDField;
        }
        set {
            this.customerIDField = value;
        }
    }
    
    /// <remarks/>
    public string AccountID {
        get {
            return this.accountIDField;
        }
        set {
            this.accountIDField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerTaxID {
        get {
            return this.customerTaxIDField;
        }
        set {
            this.customerTaxIDField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public string Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
    
    /// <remarks/>
    public AddressStructure BillingAddress {
        get {
            return this.billingAddressField;
        }
        set {
            this.billingAddressField = value;
        }
    }
    
    /// <remarks/>
    public AddressStructure ShipToAddress {
        get {
            return this.shipToAddressField;
        }
        set {
            this.shipToAddressField = value;
        }
    }
    
    /// <remarks/>
    public string Telephone {
        get {
            return this.telephoneField;
        }
        set {
            this.telephoneField = value;
        }
    }
    
    /// <remarks/>
    public string Fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string Website {
        get {
            return this.websiteField;
        }
        set {
            this.websiteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string SelfBillingIndicator {
        get {
            return this.selfBillingIndicatorField;
        }
        set {
            this.selfBillingIndicatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute("ShipToAddress", Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class AddressStructure {
    
    private string buildingNumberField;
    
    private string streetNameField;
    
    private string addressDetailField;
    
    private string cityField;
    
    private string postalCodeField;
    
    private string regionField;
    
    private string countryField;
    
    /// <remarks/>
    public string BuildingNumber {
        get {
            return this.buildingNumberField;
        }
        set {
            this.buildingNumberField = value;
        }
    }
    
    /// <remarks/>
    public string StreetName {
        get {
            return this.streetNameField;
        }
        set {
            this.streetNameField = value;
        }
    }
    
    /// <remarks/>
    public string AddressDetail {
        get {
            return this.addressDetailField;
        }
        set {
            this.addressDetailField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class GeneralLedger {
    
    private string accountIDField;
    
    private string accountDescriptionField;
    
    private decimal openingDebitBalanceField;
    
    private decimal openingCreditBalanceField;
    
    /// <remarks/>
    public string AccountID {
        get {
            return this.accountIDField;
        }
        set {
            this.accountIDField = value;
        }
    }
    
    /// <remarks/>
    public string AccountDescription {
        get {
            return this.accountDescriptionField;
        }
        set {
            this.accountDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public decimal OpeningDebitBalance {
        get {
            return this.openingDebitBalanceField;
        }
        set {
            this.openingDebitBalanceField = value;
        }
    }
    
    /// <remarks/>
    public decimal OpeningCreditBalance {
        get {
            return this.openingCreditBalanceField;
        }
        set {
            this.openingCreditBalanceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class Product {
    
    private ProductType productTypeField;
    
    private string productCodeField;
    
    private string productGroupField;
    
    private string productDescriptionField;
    
    private string productNumberCodeField;
    
    /// <remarks/>
    public ProductType ProductType {
        get {
            return this.productTypeField;
        }
        set {
            this.productTypeField = value;
        }
    }
    
    /// <remarks/>
    public string ProductCode {
        get {
            return this.productCodeField;
        }
        set {
            this.productCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ProductGroup {
        get {
            return this.productGroupField;
        }
        set {
            this.productGroupField = value;
        }
    }
    
    /// <remarks/>
    public string ProductDescription {
        get {
            return this.productDescriptionField;
        }
        set {
            this.productDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string ProductNumberCode {
        get {
            return this.productNumberCodeField;
        }
        set {
            this.productNumberCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public enum ProductType {
    
    /// <remarks/>
    P,
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    O,
    
    /// <remarks/>
    I,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class Supplier {
    
    private string supplierIDField;
    
    private string accountIDField;
    
    private string supplierTaxIDField;
    
    private string companyNameField;
    
    private string contactField;
    
    private SupplierAddressStructure billingAddressField;
    
    private SupplierAddressStructure shipFromAddressField;
    
    private string telephoneField;
    
    private string faxField;
    
    private string emailField;
    
    private string websiteField;
    
    private string selfBillingIndicatorField;
    
    /// <remarks/>
    public string SupplierID {
        get {
            return this.supplierIDField;
        }
        set {
            this.supplierIDField = value;
        }
    }
    
    /// <remarks/>
    public string AccountID {
        get {
            return this.accountIDField;
        }
        set {
            this.accountIDField = value;
        }
    }
    
    /// <remarks/>
    public string SupplierTaxID {
        get {
            return this.supplierTaxIDField;
        }
        set {
            this.supplierTaxIDField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public string Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
    
    /// <remarks/>
    public SupplierAddressStructure BillingAddress {
        get {
            return this.billingAddressField;
        }
        set {
            this.billingAddressField = value;
        }
    }
    
    /// <remarks/>
    public SupplierAddressStructure ShipFromAddress {
        get {
            return this.shipFromAddressField;
        }
        set {
            this.shipFromAddressField = value;
        }
    }
    
    /// <remarks/>
    public string Telephone {
        get {
            return this.telephoneField;
        }
        set {
            this.telephoneField = value;
        }
    }
    
    /// <remarks/>
    public string Fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string Website {
        get {
            return this.websiteField;
        }
        set {
            this.websiteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string SelfBillingIndicator {
        get {
            return this.selfBillingIndicatorField;
        }
        set {
            this.selfBillingIndicatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class TaxTable {
    
    private TaxTableEntry[] taxTableEntryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxTableEntry")]
    public TaxTableEntry[] TaxTableEntry {
        get {
            return this.taxTableEntryField;
        }
        set {
            this.taxTableEntryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class TaxTableEntry {
    
    private TaxType taxTypeField;
    
    private string taxCountryRegionField;
    
    private string taxCodeField;
    
    private string descriptionField;
    
    private System.DateTime taxExpirationDateField;
    
    private bool taxExpirationDateFieldSpecified;
    
    private decimal itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    public TaxType TaxType {
        get {
            return this.taxTypeField;
        }
        set {
            this.taxTypeField = value;
        }
    }
    
    /// <remarks/>
    public string TaxCountryRegion {
        get {
            return this.taxCountryRegionField;
        }
        set {
            this.taxCountryRegionField = value;
        }
    }
    
    /// <remarks/>
    public string TaxCode {
        get {
            return this.taxCodeField;
        }
        set {
            this.taxCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TaxExpirationDate {
        get {
            return this.taxExpirationDateField;
        }
        set {
            this.taxExpirationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaxExpirationDateSpecified {
        get {
            return this.taxExpirationDateFieldSpecified;
        }
        set {
            this.taxExpirationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxAmount", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("TaxPercentage", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public enum TaxType {
    
    /// <remarks/>
    IVA,
    
    /// <remarks/>
    IS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    TaxAmount,
    
    /// <remarks/>
    TaxPercentage,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class GeneralLedgerEntries {
    
    private string numberOfEntriesField;
    
    private decimal totalDebitField;
    
    private decimal totalCreditField;
    
    private GeneralLedgerEntriesJournal[] journalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NumberOfEntries {
        get {
            return this.numberOfEntriesField;
        }
        set {
            this.numberOfEntriesField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalDebit {
        get {
            return this.totalDebitField;
        }
        set {
            this.totalDebitField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalCredit {
        get {
            return this.totalCreditField;
        }
        set {
            this.totalCreditField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Journal")]
    public GeneralLedgerEntriesJournal[] Journal {
        get {
            return this.journalField;
        }
        set {
            this.journalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
public partial class GeneralLedgerEntriesJournal {
    
    private string journalIDField;
    
    private string descriptionField;
    
    private GeneralLedgerEntriesJournalTransaction[] transactionField;
    
    /// <remarks/>
    public string JournalID {
        get {
            return this.journalIDField;
        }
        set {
            this.journalIDField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Transaction")]
    public GeneralLedgerEntriesJournalTransaction[] Transaction {
        get {
            return this.transactionField;
        }
        set {
            this.transactionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
public partial class GeneralLedgerEntriesJournalTransaction {
    
    private string transactionIDField;
    
    private string periodField;
    
    private System.DateTime transactionDateField;
    
    private string sourceIDField;
    
    private string descriptionField;
    
    private string docArchivalNumberField;
    
    private TransactionType transactionTypeField;
    
    private System.DateTime gLPostingDateField;
    
    private string customerIDField;
    
    private string supplierIDField;
    
    private GeneralLedgerEntriesJournalTransactionLine[] lineField;
    
    /// <remarks/>
    public string TransactionID {
        get {
            return this.transactionIDField;
        }
        set {
            this.transactionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TransactionDate {
        get {
            return this.transactionDateField;
        }
        set {
            this.transactionDateField = value;
        }
    }
    
    /// <remarks/>
    public string SourceID {
        get {
            return this.sourceIDField;
        }
        set {
            this.sourceIDField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string DocArchivalNumber {
        get {
            return this.docArchivalNumberField;
        }
        set {
            this.docArchivalNumberField = value;
        }
    }
    
    /// <remarks/>
    public TransactionType TransactionType {
        get {
            return this.transactionTypeField;
        }
        set {
            this.transactionTypeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime GLPostingDate {
        get {
            return this.gLPostingDateField;
        }
        set {
            this.gLPostingDateField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerID {
        get {
            return this.customerIDField;
        }
        set {
            this.customerIDField = value;
        }
    }
    
    /// <remarks/>
    public string SupplierID {
        get {
            return this.supplierIDField;
        }
        set {
            this.supplierIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Line")]
    public GeneralLedgerEntriesJournalTransactionLine[] Line {
        get {
            return this.lineField;
        }
        set {
            this.lineField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public enum TransactionType {
    
    /// <remarks/>
    N,
    
    /// <remarks/>
    R,
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    J,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
public partial class GeneralLedgerEntriesJournalTransactionLine {
    
    private string recordIDField;
    
    private string accountIDField;
    
    private string sourceDocumentIDField;
    
    private System.DateTime systemEntryDateField;
    
    private string descriptionField;
    
    private decimal itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    /// <remarks/>
    public string RecordID {
        get {
            return this.recordIDField;
        }
        set {
            this.recordIDField = value;
        }
    }
    
    /// <remarks/>
    public string AccountID {
        get {
            return this.accountIDField;
        }
        set {
            this.accountIDField = value;
        }
    }
    
    /// <remarks/>
    public string SourceDocumentID {
        get {
            return this.sourceDocumentIDField;
        }
        set {
            this.sourceDocumentIDField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime SystemEntryDate {
        get {
            return this.systemEntryDateField;
        }
        set {
            this.systemEntryDateField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CreditAmount", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("DebitAmount", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    CreditAmount,
    
    /// <remarks/>
    DebitAmount,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class SourceDocuments {
    
    private SourceDocumentsSalesInvoices salesInvoicesField;
    
    /// <remarks/>
    public SourceDocumentsSalesInvoices SalesInvoices {
        get {
            return this.salesInvoicesField;
        }
        set {
            this.salesInvoicesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
public partial class SourceDocumentsSalesInvoices {
    
    private string numberOfEntriesField;
    
    private decimal totalDebitField;
    
    private decimal totalCreditField;
    
    private SourceDocumentsSalesInvoicesInvoice[] invoiceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NumberOfEntries {
        get {
            return this.numberOfEntriesField;
        }
        set {
            this.numberOfEntriesField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalDebit {
        get {
            return this.totalDebitField;
        }
        set {
            this.totalDebitField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalCredit {
        get {
            return this.totalCreditField;
        }
        set {
            this.totalCreditField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Invoice")]
    public SourceDocumentsSalesInvoicesInvoice[] Invoice {
        get {
            return this.invoiceField;
        }
        set {
            this.invoiceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
public partial class SourceDocumentsSalesInvoicesInvoice {
    
    private string invoiceNoField;
    
    private InvoiceStatus invoiceStatusField;
    
    private string hashField;
    
    private string hashControlField;
    
    private string periodField;
    
    private System.DateTime invoiceDateField;
    
    private InvoiceType invoiceTypeField;
    
    private string selfBillingIndicatorField;
    
    private System.DateTime systemEntryDateField;
    
    private string transactionIDField;
    
    private string customerIDField;
    
    private ShippingPointStructure shipToField;
    
    private ShippingPointStructure shipFromField;
    
    private SourceDocumentsSalesInvoicesInvoiceLine[] lineField;
    
    private SourceDocumentsSalesInvoicesInvoiceDocumentTotals documentTotalsField;
    
    /// <remarks/>
    public string InvoiceNo {
        get {
            return this.invoiceNoField;
        }
        set {
            this.invoiceNoField = value;
        }
    }
    
    /// <remarks/>
    public InvoiceStatus InvoiceStatus {
        get {
            return this.invoiceStatusField;
        }
        set {
            this.invoiceStatusField = value;
        }
    }
    
    /// <remarks/>
    public string Hash {
        get {
            return this.hashField;
        }
        set {
            this.hashField = value;
        }
    }
    
    /// <remarks/>
    public string HashControl {
        get {
            return this.hashControlField;
        }
        set {
            this.hashControlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime InvoiceDate {
        get {
            return this.invoiceDateField;
        }
        set {
            this.invoiceDateField = value;
        }
    }
    
    /// <remarks/>
    public InvoiceType InvoiceType {
        get {
            return this.invoiceTypeField;
        }
        set {
            this.invoiceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string SelfBillingIndicator {
        get {
            return this.selfBillingIndicatorField;
        }
        set {
            this.selfBillingIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime SystemEntryDate {
        get {
            return this.systemEntryDateField;
        }
        set {
            this.systemEntryDateField = value;
        }
    }
    
    /// <remarks/>
    public string TransactionID {
        get {
            return this.transactionIDField;
        }
        set {
            this.transactionIDField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerID {
        get {
            return this.customerIDField;
        }
        set {
            this.customerIDField = value;
        }
    }
    
    /// <remarks/>
    public ShippingPointStructure ShipTo {
        get {
            return this.shipToField;
        }
        set {
            this.shipToField = value;
        }
    }
    
    /// <remarks/>
    public ShippingPointStructure ShipFrom {
        get {
            return this.shipFromField;
        }
        set {
            this.shipFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Line")]
    public SourceDocumentsSalesInvoicesInvoiceLine[] Line {
        get {
            return this.lineField;
        }
        set {
            this.lineField = value;
        }
    }
    
    /// <remarks/>
    public SourceDocumentsSalesInvoicesInvoiceDocumentTotals DocumentTotals {
        get {
            return this.documentTotalsField;
        }
        set {
            this.documentTotalsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public enum InvoiceStatus {
    
    /// <remarks/>
    N,
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    F,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public enum InvoiceType {
    
    /// <remarks/>
    FT,
    
    /// <remarks/>
    FS,
    
    /// <remarks/>
    ND,
    
    /// <remarks/>
    NC,
    
    /// <remarks/>
    VD,
    
    /// <remarks/>
    TV,
    
    /// <remarks/>
    TD,
    
    /// <remarks/>
    AA,
    
    /// <remarks/>
    DA,
    
    /// <remarks/>
    RP,
    
    /// <remarks/>
    RE,
    
    /// <remarks/>
    CS,
    
    /// <remarks/>
    LD,
    
    /// <remarks/>
    RA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute("ShipFrom", Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class ShippingPointStructure {
    
    private string deliveryIDField;
    
    private System.DateTime deliveryDateField;
    
    private bool deliveryDateFieldSpecified;
    
    private AddressStructure addressField;
    
    /// <remarks/>
    public string DeliveryID {
        get {
            return this.deliveryIDField;
        }
        set {
            this.deliveryIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DeliveryDate {
        get {
            return this.deliveryDateField;
        }
        set {
            this.deliveryDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeliveryDateSpecified {
        get {
            return this.deliveryDateFieldSpecified;
        }
        set {
            this.deliveryDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public AddressStructure Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
public partial class SourceDocumentsSalesInvoicesInvoiceLine {
    
    private string lineNumberField;
    
    private OrderReferences[] orderReferencesField;
    
    private string productCodeField;
    
    private string productDescriptionField;
    
    private decimal quantityField;
    
    private string unitOfMeasureField;
    
    private decimal unitPriceField;
    
    private System.DateTime taxPointDateField;
    
    private References referencesField;
    
    private string descriptionField;
    
    private decimal itemField;
    
    private ItemChoiceType2 itemElementNameField;
    
    private Tax taxField;
    
    private string taxExemptionReasonField;
    
    private decimal settlementAmountField;
    
    private bool settlementAmountFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string LineNumber {
        get {
            return this.lineNumberField;
        }
        set {
            this.lineNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrderReferences")]
    public OrderReferences[] OrderReferences {
        get {
            return this.orderReferencesField;
        }
        set {
            this.orderReferencesField = value;
        }
    }
    
    /// <remarks/>
    public string ProductCode {
        get {
            return this.productCodeField;
        }
        set {
            this.productCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ProductDescription {
        get {
            return this.productDescriptionField;
        }
        set {
            this.productDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public decimal Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public string UnitOfMeasure {
        get {
            return this.unitOfMeasureField;
        }
        set {
            this.unitOfMeasureField = value;
        }
    }
    
    /// <remarks/>
    public decimal UnitPrice {
        get {
            return this.unitPriceField;
        }
        set {
            this.unitPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TaxPointDate {
        get {
            return this.taxPointDateField;
        }
        set {
            this.taxPointDateField = value;
        }
    }
    
    /// <remarks/>
    public References References {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CreditAmount", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("DebitAmount", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType2 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    public Tax Tax {
        get {
            return this.taxField;
        }
        set {
            this.taxField = value;
        }
    }
    
    /// <remarks/>
    public string TaxExemptionReason {
        get {
            return this.taxExemptionReasonField;
        }
        set {
            this.taxExemptionReasonField = value;
        }
    }
    
    /// <remarks/>
    public decimal SettlementAmount {
        get {
            return this.settlementAmountField;
        }
        set {
            this.settlementAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SettlementAmountSpecified {
        get {
            return this.settlementAmountFieldSpecified;
        }
        set {
            this.settlementAmountFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class OrderReferences {
    
    private string originatingONField;
    
    private System.DateTime orderDateField;
    
    private bool orderDateFieldSpecified;
    
    /// <remarks/>
    public string OriginatingON {
        get {
            return this.originatingONField;
        }
        set {
            this.originatingONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime OrderDate {
        get {
            return this.orderDateField;
        }
        set {
            this.orderDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrderDateSpecified {
        get {
            return this.orderDateFieldSpecified;
        }
        set {
            this.orderDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class References {
    
    private CreditNote creditNoteField;
    
    /// <remarks/>
    public CreditNote CreditNote {
        get {
            return this.creditNoteField;
        }
        set {
            this.creditNoteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class CreditNote {
    
    private string referenceField;
    
    private string reasonField;
    
    /// <remarks/>
    public string Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    public string Reason {
        get {
            return this.reasonField;
        }
        set {
            this.reasonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IncludeInSchema=false)]
public enum ItemChoiceType2 {
    
    /// <remarks/>
    CreditAmount,
    
    /// <remarks/>
    DebitAmount,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class Tax {
    
    private TaxType taxTypeField;
    
    private string taxCountryRegionField;
    
    private string taxCodeField;
    
    private decimal itemField;
    
    private ItemChoiceType3 itemElementNameField;
    
    /// <remarks/>
    public TaxType TaxType {
        get {
            return this.taxTypeField;
        }
        set {
            this.taxTypeField = value;
        }
    }
    
    /// <remarks/>
    public string TaxCountryRegion {
        get {
            return this.taxCountryRegionField;
        }
        set {
            this.taxCountryRegionField = value;
        }
    }
    
    /// <remarks/>
    public string TaxCode {
        get {
            return this.taxCodeField;
        }
        set {
            this.taxCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxAmount", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("TaxPercentage", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType3 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IncludeInSchema=false)]
public enum ItemChoiceType3 {
    
    /// <remarks/>
    TaxAmount,
    
    /// <remarks/>
    TaxPercentage,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
public partial class SourceDocumentsSalesInvoicesInvoiceDocumentTotals {
    
    private decimal taxPayableField;
    
    private decimal netTotalField;
    
    private decimal grossTotalField;
    
    private Currency currencyField;
    
    private Settlement settlementField;
    
    /// <remarks/>
    public decimal TaxPayable {
        get {
            return this.taxPayableField;
        }
        set {
            this.taxPayableField = value;
        }
    }
    
    /// <remarks/>
    public decimal NetTotal {
        get {
            return this.netTotalField;
        }
        set {
            this.netTotalField = value;
        }
    }
    
    /// <remarks/>
    public decimal GrossTotal {
        get {
            return this.grossTotalField;
        }
        set {
            this.grossTotalField = value;
        }
    }
    
    /// <remarks/>
    public Currency Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public Settlement Settlement {
        get {
            return this.settlementField;
        }
        set {
            this.settlementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class Currency {
    
    private string currencyCodeField;
    
    private decimal itemField;
    
    private ItemChoiceType4 itemElementNameField;
    
    /// <remarks/>
    public string CurrencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CurrencyCreditAmount", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("CurrencyDebitAmount", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType4 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IncludeInSchema=false)]
public enum ItemChoiceType4 {
    
    /// <remarks/>
    CurrencyCreditAmount,
    
    /// <remarks/>
    CurrencyDebitAmount,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public partial class Settlement {
    
    private string settlementDiscountField;
    
    private decimal settlementAmountField;
    
    private bool settlementAmountFieldSpecified;
    
    private System.DateTime settlementDateField;
    
    private bool settlementDateFieldSpecified;
    
    private PaymentMechanism paymentMechanismField;
    
    private bool paymentMechanismFieldSpecified;
    
    /// <remarks/>
    public string SettlementDiscount {
        get {
            return this.settlementDiscountField;
        }
        set {
            this.settlementDiscountField = value;
        }
    }
    
    /// <remarks/>
    public decimal SettlementAmount {
        get {
            return this.settlementAmountField;
        }
        set {
            this.settlementAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SettlementAmountSpecified {
        get {
            return this.settlementAmountFieldSpecified;
        }
        set {
            this.settlementAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime SettlementDate {
        get {
            return this.settlementDateField;
        }
        set {
            this.settlementDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SettlementDateSpecified {
        get {
            return this.settlementDateFieldSpecified;
        }
        set {
            this.settlementDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PaymentMechanism PaymentMechanism {
        get {
            return this.paymentMechanismField;
        }
        set {
            this.paymentMechanismField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PaymentMechanismSpecified {
        get {
            return this.paymentMechanismFieldSpecified;
        }
        set {
            this.paymentMechanismFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:OECD:StandardAuditFile-Tax:PT_1.01_01", IsNullable=false)]
public enum PaymentMechanism {
    
    /// <remarks/>
    NU,
    
    /// <remarks/>
    CH,
    
    /// <remarks/>
    CD,
    
    /// <remarks/>
    CC,
    
    /// <remarks/>
    TB,
    
    /// <remarks/>
    TR,
}
